<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dataWeb" nsURI="http://www.example.org/dataWeb" nsPrefix="dataWeb">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Application">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="R01_UnicaIndexHome R04_SocialRSS R06b_MinSurvey"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="R01_UnicaIndexHome" value="entity.pageconfig->select(pc | pc.pageType = PageType::Index)->size() = 1"/>
      <details key="R04_SocialRSS" value="socialcontent->select(sc |&#xA;&#x9;&#x9;&#x9;&#x9;sc.type = SocialType::Twitter or sc.type = SocialType::Facebook)->size() >= 1 and socialcontent->select(sc |&#xA;&#x9;&#x9;&#x9;&#x9;sc.type = SocialType::RSS)->size() >= 1"/>
      <details key="R06b_MinSurvey" value="page->select(p | p.oclIsKindOf(SurveyPage))->size() >= 1"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" upperBound="-1"
        eType="#//Entity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="page" lowerBound="1" upperBound="-1"
        eType="#//Page" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="socialcontent" upperBound="-1"
        eType="#//SocialContent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="role" upperBound="-1" eType="#//Role"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entity">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="R02_CRUDIncompatible R03_IndiceDetalle R05_NoSelfReference R08_UniqueIndexPerEntity"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="R02_CRUDIncompatible" value="pageconfig->exists(pc | pc.pageType = PageType::CRUD) implies pageconfig->forAll(pc&#xA;&#x9;&#x9;&#x9;&#x9;| pc.pageType = PageType::CRUD)"/>
      <details key="R03_IndiceDetalle" value="(pageconfig->exists(pc |&#xA;&#x9;&#x9;&#x9;&#x9;pc.pageType = PageType::Index or pc.pageType = PageType::ExtendedIndex) implies pageconfig->exists(pc |&#xA;&#x9;&#x9;&#x9;&#x9;pc.pageType = PageType::Detail or pc.pageType = PageType::IndexDetail)) and (pageconfig->exists(pc |&#xA;&#x9;&#x9;&#x9;&#x9;pc.pageType = PageType::Detail or pc.pageType = PageType::IndexDetail) implies pageconfig->exists(pc |&#xA;&#x9;&#x9;&#x9;&#x9;pc.pageType = PageType::Index or pc.pageType = PageType::ExtendedIndex))"/>
      <details key="R05_NoSelfReference" value="reference->forAll(ref | ref.name &lt;> name)"/>
      <details key="R08_UniqueIndexPerEntity" value="pageconfig->select(pc | pc.pageType = PageType::Index)->size() &lt;= 1"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" upperBound="-1"
        eType="#//Attribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" upperBound="-1"
        eType="#//Reference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pageconfig" upperBound="-1"
        eType="#//PageConfig" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reference">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicity" eType="#//Multiplicity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//DataType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Page" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="link" upperBound="-1" eType="#//Link"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="socialcontent" eType="#//SocialContent"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaDescription" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaKeywords" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PageConfig">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="R09_ValidIndexAttributes"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="R09_ValidIndexAttributes" value="attribute &lt;> null implies let parent : dataWeb::Entity =&#xA;&#x9;&#x9;&#x9;self.oclContainer().oclAsType(dataWeb::Entity)&#xA;&#x9;in parent.attribute->includes(self.attribute)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pagination" upperBound="-1"
        eType="#//Pagination" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pageType" eType="#//PageType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" eType="#//Attribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntityPage" abstract="true" eSuperTypes="#//Page">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" eType="#//Entity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SurveyPage" eSuperTypes="#//Page">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="R07_ResponsesDefined"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="R07_ResponsesDefined" value="survey.question->forAll(q |&#xA;&#x9;&#x9;&#x9;(q.oclIsKindOf(TrueFalseQuestion) implies q.oclAsType(TrueFalseQuestion).correctAnswer = true or q.oclAsType(TrueFalseQuestion).correctAnswer = false) and (q.oclIsKindOf(MCQuestion) implies q.oclAsType(MCQuestion).option->size() > 0))"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="survey" lowerBound="1"
        upperBound="-1" eType="#//Survey" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SocialContent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//SocialType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="R12_AdminMustSeeSurvey"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="R12_AdminMustSeeSurvey" value="self.permissions = dataWeb::PermissionType::ADMIN implies self.accessiblePages->exists(p :&#xA;&#x9;&#x9;&#x9;Page | p.oclIsKindOf(dataWeb::SurveyPage))"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="permissions" eType="#//PermissionType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="accessiblePages" upperBound="-1"
        eType="#//Page"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numeroEntidadesAccesibles"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="derivation" value="self.accessiblePages->select(p | p.oclIsKindOf(EntityPage))->collect(p |&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;p.oclAsType(EntityPage).entity)->asSet()->size()"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="paginasMediasAccesibles"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="derivation" value="let totalPaginas = self.accessiblePages->size() , app = dataWeb::Application.allInstances()->any(a |&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;a.role->includes(self)) , totalRoles = app.role->size()&#xA;&#x9;in totalPaginas / totalRoles"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Link">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="externalURL" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pagination">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pageSize" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Survey">
    <eStructuralFeatures xsi:type="ecore:EReference" name="question" lowerBound="1"
        upperBound="-1" eType="#//Question" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="representation" eType="#//ChartType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numeroPregVF" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" volatile="true"
        transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="D03: número de preguntas Verdadero/Falso"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="derivation" value="self.question->select(q | q.oclIsKindOf(TrueFalseQuestion))->size()"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numeroPregSelect" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" volatile="true"
        transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="D04: número de preguntas de selección múltiple"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="derivation" value="self.question->select(q | q.oclIsKindOf(MCQuestion))->size()"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Question" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isMandatory" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MCQuestion" eSuperTypes="#//Question">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="R10_MandatoryMCQuestionsHaveOptions"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="R10_MandatoryMCQuestionsHaveOptions" value="self.isMandatory implies self.option->size() > 0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="option" lowerBound="1"
        upperBound="-1" eType="#//AnswerOption" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TrueFalseQuestion" eSuperTypes="#//Question">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="R11_MandatoryTFQuestionsHaveAnswer"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="R11_MandatoryTFQuestionsHaveAnswer" value="self.isMandatory implies (self.correctAnswer = true or self.correctAnswer = false)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="correctAnswer" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ShortQuestion" eSuperTypes="#//Question"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnswerOption">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DataType">
    <eLiterals name="Integer"/>
    <eLiterals name="Boolean" value="1"/>
    <eLiterals name="String" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PageType">
    <eLiterals name="Create"/>
    <eLiterals name="Index" value="1"/>
    <eLiterals name="ExtendedIndex" value="2"/>
    <eLiterals name="IndexDetail" value="3"/>
    <eLiterals name="Detail" value="4"/>
    <eLiterals name="Update" value="5"/>
    <eLiterals name="Delete" value="6"/>
    <eLiterals name="CRUD" value="7"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SocialType">
    <eLiterals name="Twitter"/>
    <eLiterals name="Facebook" value="1"/>
    <eLiterals name="RSS" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ChartType">
    <eLiterals name="Text"/>
    <eLiterals name="Bar" value="1"/>
    <eLiterals name="Pie" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Multiplicity">
    <eLiterals name="ZERO_ONE"/>
    <eLiterals name="ONE_ONE" value="1"/>
    <eLiterals name="ZERO_MANY" value="2"/>
    <eLiterals name="ONE_MANY" value="3"/>
    <eLiterals name="MANY_MANY" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PermissionType">
    <eLiterals name="READ"/>
    <eLiterals name="WRITE" value="1"/>
    <eLiterals name="ADMIN" value="2"/>
  </eClassifiers>
</ecore:EPackage>
